### ISSUE TITLE
Method exportTouchstone on develop branch does not output properly

### ISSUE THREAD

**Issue by leoremil** [umbertozanovello/CoSimPy#5]
I was trying to export the final S-matrix after adding capacitors and matching networks to my RF coil as a touchstone file, however upon importing the touchstone file in Matlab the spectrum was very different from the one in CoSimPy. I tried exporting the S-matrix as a different format but got similar erroneous results. Exporting the S-matrix as magnitude and phase gave negative magnitudes. Ultimately I had to save the S-matrix as a different file type to get the correct results.

**Comment by umbertozanovello** [comment]
There was a bug in the method that caused the Touchstone to be exported as 'RI' independently of the options["format"] passed as an argument. Now it should be solved. Be aware that the bug is still present in the Main branch.
Thanks a lot for spotting it!
